on:
  push:
    branches: [main]
  pull_request:
name: Test
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.25.x, 1.26.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]
        package: [passthrough, extras]
    runs-on: ${{ matrix.platform }}
    defaults:
      run:
        shell: bash
    steps:
      - name: Install Go
        uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
        with:
          go-version: ${{ matrix.go-version }}
          cache: false
      - name: Install staticcheck
        if: matrix.platform == 'ubuntu-latest'
        run: go install honnef.co/go/tools/cmd/staticcheck@latest
      - name: Update PATH
        run: echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
      - name: Checkout code
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
      - name: Fmt
        if: matrix.platform != 'windows-latest'
        run: "diff <(gofmt -d .) <(printf '')"
        working-directory: ${{ matrix.package }}
      - name: Vet
        run: go vet ./...
        working-directory: ${{ matrix.package }}
      - name: Staticcheck
        if: matrix.platform == 'ubuntu-latest'
        run: staticcheck ./...
        working-directory: ${{ matrix.package }}
      - name: Test
        run: go test -race ./...
        working-directory: ${{ matrix.package }}
