on:
  push:
    branches: [main]
  pull_request:
name: Test
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.20.x, 1.21.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]
        package: [passthrough]
    runs-on: ${{ matrix.platform }}
    defaults:
      run:
        shell: bash
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          cache: false
      - name: Install staticcheck
        if: matrix.platform == 'ubuntu-latest'
        run: go install honnef.co/go/tools/cmd/staticcheck@latest
      - name: Update PATH
        run: echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Fmt
        if: matrix.platform != 'windows-latest'
        run: "diff <(gofmt -d .) <(printf '')"
        working-directory: ${{ matrix.package }}
      - name: Vet
        run: go vet ./...
        working-directory: ${{ matrix.package }}
      - name: Staticcheck
        if: matrix.platform == 'ubuntu-latest'
        run: staticcheck ./...
        working-directory: ${{ matrix.package }}
      - name: Test
        run: go test -race ./...
        working-directory: ${{ matrix.package }}
